spring.application.name=Insight-Service
server.port=8086

spring.ai.ollama.chat.model=qwen2.5:3b
spring.ai.ollama.init.pull-model-strategy=never

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}